<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Dapper.Extensions.PostgreSQL" Version="5.4.2" />
    <PackageVersion Include="FluentMigrator.Runner.Postgres" Version="8.0.1" />
    <PackageVersion Include="KafkaFlow" Version="4.2.0" />
    <PackageVersion Include="KafkaFlow.BatchConsume" Version="2.5.1" />
    <PackageVersion Include="KafkaFlow.LogHandler.Microsoft" Version="4.2.0" />
    <PackageVersion Include="KafkaFlow.Microsoft.DependencyInjection" Version="4.2.0" />
    <PackageVersion Include="KafkaFlow.Serializer.JsonCore" Version="4.2.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Resilience" Version="10.4.0" />
    <PackageVersion Include="Npgsql" Version="10.0.2" />
    <PackageVersion Include="Polly" Version="8.6.6" />
    <PackageVersion Include="Polly.Core" Version="8.6.6" />
    <PackageVersion Include="Polly.Extensions" Version="8.6.6" />
  </ItemGroup>
</Project>