<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Dapper.Extensions.PostgreSQL" Version="5.4.2" />
    <PackageVersion Include="Ductus.FluentDocker" Version="2.85.0" />
    <PackageVersion Include="Ductus.FluentDocker.XUnit" Version="2.85.0" />
    <PackageVersion Include="FluentAssertions" Version="8.9.0" />
    <PackageVersion Include="FluentMigrator.Runner.Postgres" Version="8.0.1" />
    <PackageVersion Include="KafkaFlow" Version="4.2.0" />
    <PackageVersion Include="KafkaFlow.BatchConsume" Version="2.5.1" />
    <PackageVersion Include="KafkaFlow.LogHandler.Microsoft" Version="4.2.0" />
    <PackageVersion Include="KafkaFlow.Microsoft.DependencyInjection" Version="4.2.0" />
    <PackageVersion Include="KafkaFlow.Retry" Version="3.1.0" />
    <PackageVersion Include="KafkaFlow.Serializer.JsonCore" Version="4.2.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Resilience" Version="10.4.0" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Npgsql" Version="10.0.2" />
    <PackageVersion Include="Polly" Version="8.6.6" />
    <PackageVersion Include="Polly.Core" Version="8.6.6" />
    <PackageVersion Include="Polly.Extensions" Version="8.6.6" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageVersion Include="xunit.v3.assert" Version="3.2.2" />
    <PackageVersion Include="xunit.v3.core" Version="3.2.2" />
  </ItemGroup>
</Project>